all: lab2A.c lab2B.c lab2C.c
	gcc -o lab2A lab2A.c -g3 -O0 -z execstack -fno-stack-protector -no-pie -D_FORTIFY_SOURCE=0
	gcc -o lab2B lab2B.c -g3 -O0 -z execstack -fno-stack-protector -no-pie -D_FORTIFY_SOURCE=0
	gcc -o lab2C lab2C.c -g3 -O0 -z execstack -fno-stack-protector -no-pie -D_FORTIFY_SOURCE=0
